### ISSUE TITLE
TypeError: file.bytes is not a function exception on file uploaded

### ISSUE THREAD

**Issue by Dodo9128** [zhengkyl/qrframe#2]
Hello
I was very impressed with your wonderful service

An error is currently occurring when uploading the image.

Is there a limited format of files that can be uploaded?
I tried to upload a file in png format

thx

![스크린샷 2024-10-02 오전 11 17 11](https://github.com/user-attachments/assets/b0a729c8-8cc3-4a65-92fd-3057018366a2)
![스크린샷 2024-10-02 오전 11 17 18](https://github.com/user-attachments/assets/b0c68bf5-988f-4f5f-a188-a5e0a9cc0dd6)

**Comment by zhengkyl** [comment]
Thanks for reporting this error!

It turns out `file.bytes()` is supported by Firefox and Safari, but not Chrome. I have changed that code to work in all browsers. https://developer.mozilla.org/en-US/docs/Web/API/Response/bytes

It should work now, png, jpg and svg should all be supported.

**Comment by Dodo9128** [comment]
I made sure the feature works correctly! Thank you for your quick response🤩
